### PR TITLE
Add alpine variants

### PR DESCRIPTION
**Pull request by tianon**
Closes #41 (changes carried here -- see first commit)

This includes updates to `generate-stackbrew-library.sh`, and improves consistency both between Debian and Alpine, and between these Alpine variants and other docker-library Alpine variants. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
Argh, assumptions in the test we wrote breaking Travis here -- I'll take a closer look at the tests tomorrow to see if there's a simple fix. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/commit/1c9ec7d4f58c2799888f50e38f3d36ad558ab583

https://travis-ci.org/docker-library/logstash/builds/181799642 :+1:

**Comment by mi-hol** [comment]
@tianon I'm a bit lost because #2429 is flagged as merged but 
https://github.com/docker-library/repo-info/blob/master/repos/logstash/tag-details.md#logstash502-alpine (need to copy URL string manually due to git bug!)
contains 'does not exist (yet?)'
1) Any hint how/where I can get the latest alpine based logstash version?
2) the used tag 'alpine' seems to mean 'latest-alpine', to clarify this purpose I'd recommend to rename it

**Comment by tianon** [comment]
@mi-hol they should be up now -- they do take a little time to build/push after we merge

The `alpine` tag is the Alpine variant which corresponds to the `latest` tag.  The reason we don't call it `latest-alpine` is that `latest` in Docker is really a misnomer to begin with.  Something like `default` would've been more accurate, since it's simply the tag that is implied if no tag is specified.  That being said, we don't recommend that users use `:latest` (and instead recommend that they depend on a specific version or release track, such as `logstash:5.0` or `logstash:5`), and only provide `:latest` for the case of not specifying a tag at all, ie, unadorned `logstash`.  Thus, the Alpine-based variant of the `logstash` image is `logstash:alpine`, similar to how `logstash:5` becomes `logstash:5-alpine`.

**Pull request merged**
