### PR TITLE
Update default config to ensure logs go to stdout

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
As noted in https://github.com/docker-library/logstash/issues/63#issuecomment-258143959 :+1:

**Comment by tianon** [comment]
Arg, this doesn't actually do it properly either; this just redirects the logs to `/usr/share/logstash/logs` instead.

**Comment by tianon** [comment]
I'm not actually convinced this ever worked "properly".

**Comment by tianon** [comment]
Alright, this does the trick:

```
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties.
The stdin plugin is now waiting for input:
17:19:01.908 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000}
17:19:01.926 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started
17:19:02.019 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
hi
{
    "@timestamp" => 2016-11-03T17:19:15.246Z,
      "@version" => "1",
          "host" => "c787ae30890b",
       "message" => "hi",
          "type" => "stdin"
}
```

**Comment by tianon** [comment]
Updated just to have it make a backup of the original `log4j2.properties` file. :+1:

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
