### PR TITLE
Update libzmq3->libzmq5

### PR DESCRIPTION
**Pull request by tianon**
https://packages.debian.org/source/stretch/zeromq3

### CODE REVIEW

**Comment by tianon** [comment]
Heh, https://github.com/docker-library/openjdk/pull/124 isn't officially built yet (even though https://github.com/docker-library/official-images/pull/3147 merged).

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/3156 for the next bit we need before this works again.

**Comment by tianon** [comment]
Looks like 2.x is now being hit by https://wiki.debian.org/Teams/Apt/Sha1Removal (https://github.com/elastic/logstash/issues/5761).

**Edit:** full log, for posterity:
```console
...
/etc/apt/trusted.gpg.d/elastic.gpg
----------------------------------
pub   rsa2048 2013-09-16 [SC]
      4609 5ACC 8548 582C 1A26  99A9 D27D 666C D88E 42B4
uid           [ unknown] Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>
sub   rsa2048 2013-09-16 [E]
 ---> d81d645f3127
Removing intermediate container 6d32f3ccab02
Step 7/16 : RUN echo 'deb http://packages.elastic.co/logstash/2.4/debian stable main' > /etc/apt/sources.list.d/logstash.list
 ---> Running in 9108ac7e1431
 ---> c7a57bcc423e
Removing intermediate container 9108ac7e1431
Step 8/16 : ENV LOGSTASH_VERSION 2.4.1
 ---> Running in d80601fcc478
 ---> 688d8f9eb3f1
Removing intermediate container d80601fcc478
Step 9/16 : ENV LOGSTASH_DEB_VERSION 1:2.4.1-1
 ---> Running in 80ac745194db
 ---> 4c32d4030a2a
Removing intermediate container 80ac745194db
Step 10/16 : RUN set -x 	&& apt-get update 	&& apt-get install -y --no-install-recommends "logstash=$LOGSTASH_DEB_VERSION" 	&& rm -rf /var/lib/apt/lists/*
 ---> Running in 165a0717ab74
+ apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [88.5 kB]
Get:3 http://security.debian.org stretch/updates InRelease [62.9 kB]
Get:4 http://deb.debian.org/debian stretch Release [113 kB]
Ign:5 http://packages.elastic.co/logstash/2.4/debian stable InRelease
Get:6 http://packages.elastic.co/logstash/2.4/debian stable Release [3301 B]
Get:7 http://deb.debian.org/debian stretch Release.gpg [3108 B]
Get:8 http://packages.elastic.co/logstash/2.4/debian stable Release.gpg [490 B]
Get:9 http://security.debian.org stretch/updates/main amd64 Packages [64.9 kB]
Get:10 http://deb.debian.org/debian stretch/main amd64 Packages [9497 kB]
Ign:8 http://packages.elastic.co/logstash/2.4/debian stable Release.gpg
Get:11 http://packages.elastic.co/logstash/2.4/debian stable/main amd64 Packages [695 B]
Fetched 9834 kB in 1s (7794 kB/s)
Reading package lists...
W: GPG error: http://packages.elastic.co/logstash/2.4/debian stable Release: The following signatures were invalid: 46095ACC8548582C1A2699A9D27D666CD88E42B4
W: The repository 'http://packages.elastic.co/logstash/2.4/debian stable Release' is not signed.
+ apt-get install -y --no-install-recommends logstash=1:2.4.1-1
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  cron libpopt0 logrotate
Suggested packages:
  anacron checksecurity
Recommended packages:
  exim4 | postfix | mail-transport-agent bsd-mailx | mailx
The following NEW packages will be installed:
  cron libpopt0 logrotate logstash
0 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 85.1 MB of archives.
After this operation, 144 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  logstash
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c set -x 	&& apt-get update 	&& apt-get install -y --no-install-recommends "logstash=$LOGSTASH_DEB_VERSION" 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by tianon** [comment]
I'm thinking the way to "fix" this (for the interim between now and the full deprecation of this repo) might be to simply download and install the `.deb` file directly for 2.4.

**Comment by tianon** [comment]
Came up with a cleaner fix using `apt-get update -o APT::Hashes::SHA1::Weak=yes` (conditionally). :+1:

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
