### PR TITLE
Allow arbitrary "--user" values (skip "gosu" unless we're running as root)

### LINKED ISSUE #11: Allow to run as root / different user
Is there a compelling reason not to run Logstash in the container as root?

The problem is that the logstash user 999 will not be able to run most logs (like /log/syslog). I think it's better to run root in a Docker container and mount the volume as read-only as to change file permission in the host to allow a non-root docker user to read the logs.

I would suggest just skipping the _gosu_ or add the functionality to specify a user ID to run as when starting the container (through an env variable)...

### PR DESCRIPTION
**Pull request by tianon**
Fixes #11

See also https://github.com/docker-library/elasticsearch/pull/77

### CODE REVIEW

**Comment by tianon** [comment]
To run as another user, one currently has to use `--entrypoint` since our use of `gosu` is unconditional, but this change allows for `--user` to be used arbitrarily.

**Comment by tianon** [comment]
Hmm, turns out `/var/lib/logstash` makes this slightly more complicated.

**Comment by tianon** [comment]
`Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
22:52:37.077 [LogStash::Runner] FATAL logstash.runner - An unexpected error occurred! {:error=>#<ArgumentError: Path "/var/lib/logstash" is not a directory or not writable.>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:396:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:191:in `validate'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:182:in `validate_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:100:in `validate_all'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:99:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:224:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:175:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:68:in `(root)'"]}`

**Comment by tianon** [comment]
It _does_ work if I specify `--tmpfs /var/lib/logstash` as well, so I'm going to chalk that one up to a documentation issue (if you want to use arbitrary `--user` values, you need to also handle permissions on `/var/lib/logstash`).  Sound fair?

**Comment by yosifkit** [comment]
Sounds fair to me; just like the [MongoDB image](https://github.com/docker-library/mongo/blob/0e4966760ba48fb611d3efb3975484444b5def1e/3.2/docker-entrypoint.sh#L9).

**Pull request merged**
