### PR TITLE
Migration to Alpine

### PR DESCRIPTION
**Pull request by blackrez**
Change the image baselayer to alpine linux.

### CODE REVIEW

**Comment by willfarrell** [comment]
Very unlikely they'll merge and overwrite the use of debian. What I'm seeing other projects do is adding the alpine images in parallel. ie `2.3-alpine`

Looking forward to seeing alpine as an option here.

**Comment by yosifkit** [comment]
@willfarrell is correct. The plan is to have an alpine variant as an option, not to replace the debian version.  Also, the formatting is very different from the current files (tabs, `&&`, etc) and `gosu` is removed so that would cause the `entrypoint` script to fail.

See https://github.com/docker-library/redis/pull/40 and some of the other repos that have an alpine variant for examples.

**Comment by blackrez** [comment]
Thanks for your remarks, I will correct that and make update this pull request.

**Comment by willfarrell** [comment]
Awesome, maybe add in `5-alpine`, `5.0-alpine` and `5.0.0-alpha1-alpine` if you're feeling ambitions.

**Comment by CpuID** [comment]
big +1 to an alpine variant of this image

**Comment by shouze** [comment]
ping @blackrez. Did you have some time to make the changes? I can take on it if you didn't.
What was the size of the built image based on alpine? The current images's size are... pretty freakin for such a tool.

**Comment by mi-hol** [comment]
@yosifkit @tianon are there plans to rename & merge this change?

**Pull request closed without merging**
