### PR TITLE
Switch to apt repo

### LINKED ISSUE #3: To APT or To Bin
See discussion on https://github.com/docker-library/official-images/pull/530 for more context.

In a nutshell, it's still an open debate as to whether upstream would officially prefer we use the binaries or the debs or the APT repo.

### PR DESCRIPTION
**Pull request by yosifkit**
Fixes #3

### CODE REVIEW

**Comment by md5** [comment]
LGTM

**Comment by yosifkit** [comment]
ping @Moghedrin and @tianon

**Comment by tianon** [comment]
LGTM

cc @Moghedrin for the merge :wink:

**Comment by daghack** [comment]
LGTM

**Pull request merged**
